version: '3.8'

services:
  ex_c:
    container_name: ex_c
    build:
      context: ./ex_c
      dockerfile: ./../.devcontainer/Dockerfile
      target: ex_c
    volumes:
      - "./ex_c:/C/"
    tty: true
    networks:
      - ex-dev-net

  ex_java:
    container_name: ex_java
    build:
      context: ./ex_java/
      dockerfile: ./../.devcontainer/Dockerfile
      target: ex_java
    volumes:
      - "./ex_java:/Java/"
    tty: true
    networks:
      - ex-dev-net

  ex_python:
    container_name: ex_py
    build:
      context: ./ex_py
      dockerfile: ./../.devcontainer/Dockerfile
      target: ex_python
    env_file:
      - ./.devcontainer/ex_python/.env
    volumes:
      - "./ex_py:/Python/"
    tty: true
    networks:
      - ex-dev-net

  dev_win:
    container_name: dev_win
    build:
      context: ./dev_win
      dockerfile: ./../.devcontainer/Dockerfile
      target: dev_win
    env_file:
      - ./.devcontainer/dev_win/.env
    volumes:
      - "./dev_win:/dev_win/"
    tty: true
    networks:
      - ex-dev-net


networks:
  ex-dev-net:
    driver: bridge
